;Write a program to display a”?” read three characters, and then display them in the
;middle of an 11×11 box of asterisks.

.MODEL SMALL
.STACK 100H
.DATA
	A DB ?
	B DB ?
	D DB ?
	E DB ?
.CODE
MAIN PROC 
	MOV AX,@DATA		;INITIALIZE THE DATA SEGMENT
	MOV DS,AX
	
	MOV DL,'?'			;PRINT '?'CHARACTER
	MOV AH,2
	INT 21H
	
	MOV AH,1			;INPUT 3 CHARACTERS
	INT 21H 
	MOV A,AL
	
	INT 21H
	MOV B,AL
	
	INT 21H
	MOV D,AL
	
	MOV AH,2
	
	MOV DL,0AH		;PRINT NEWLINE
	INT 21H
	MOV DL,0DH
	INT 21H
	
	MOV CX,0CH		;OUTER LOOP COUNTER
	PRNT:				;OUTER LOOP 
		MOV E,0BH	;COUNTER FOR INNER LOOP
		DEC CX
		JNZ ITERATION
		JMP ENDCASE
	ITERATION:			;INNER LOOP
		CMP CX,6H		;AFTER FIVE ITERATION OF OUTER LOOP 
		JZ BELOW		;GO TO 'BELOW' LABEL
		
		MOV DL,'*'		;PRINT '*'CHARACTER
		INT 21H
		
		DEC E
		JNZ ITERATION
		MOV DL,0AH
		INT 21H
		MOV DL,0DH
		INT 21H
		JMP PRNT
	BELOW:				;PRINT 6TH LINE OF OUTPUT
		CMP E,0
		JE NEWLINE		;IF 6TH LINE FINISHED GO FOR PRINT THE 7TH LINE
		MOV DL,'*'
		INT 21H
		DEC E
		CMP E,7H
		JNZ BELOW
		MOV DL,A
		INT 21H
		DEC E
		MOV DL,B
		INT 21H
		DEC E
		MOV DL,D
		INT 21H
		DEC E
		JMP BELOW
	NEWLINE:			;PRINT A NEWLINE AND GO TO THE OUTER LOOP AGAIN
		MOV DL,0AH
		INT 21H
		MOV DL,0DH
		INT 21H
		JMP PRNT
	ENDCASE:			;DOS EXIT
		MOV AH,4CH
		INT 21H
	
MAIN ENDP
END MAIN
	